name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '56 4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install deps
      run: npm i -g osmtogeojson      
    - name: Get the data and analyze
      run: |
        chmod +x ./umap.sh
        ./umap.sh
        chmod +x ./count.sh
        ./count.sh
      shell: bash
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
